### ISSUE TITLE
crud files generation problem

### ISSUE THREAD

**Issue by roham96** [milwad-dev/laravel-crod#15]
![Screenshot from 2023-01-24 08-43-22](https://user-images.githubusercontent.com/30126136/214216902-298755e1-0223-4c62-9b05-968ee7fa571c.png)

please fix this proble!
os: linux

**Comment by roham96** [comment]
![Screenshot from 2023-01-24 14-46-10](https://user-images.githubusercontent.com/30126136/214278207-a004e727-632a-468f-91ef-7a5c2dc00c65.png)


that issue fixed using this :

all "\\" 's should be "//"

**Comment by milwad-dev** [comment]
There will be a new update soon, and this bug will be fixed soon.

Thanks for add issue.

**Comment by milwad-dev** [comment]
@roham96 
Now this bug corrects 
https://github.com/milwad-dev/laravel-crod/releases/tag/v1.0
